version: "3.7"
services:
  web:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: dev
      PORT: 8080
    ports:
      - "8080:8080"
    command: npm run dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  postgres:
    image: postgres
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
