version: "3.7"
services:
  web:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      REDIS_URL: redis://redis:6379
      CLIENT_URL: http://localhost:3000
      SESSION_SECRET: secret
      NODE_ENV: dev
      PORT: 8081
    ports:
      - "8081:8081"
    command: npm run dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  postgres:
    image: postgres:13
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  redis:
    image: redis
    ports:
      - "36379:6379"
